--- 
abstract: A CPANPLUS GUI Shell written in wxWidgets
author: Skaman Sam Tyler <skamansam@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPANPLUS-Shell-Wx
no_index: 
  directory: 
    - blib
    - inc
    - t
requires: 
  Class::Struct: 0.0
  Cwd: 0.0
  File::HomeDir: 0.0
  File::Spec: 0.0
  IPC::Cmd: 0.0
  Locale::Maketext::Simple: 0.0
  Module::Load: 0.0
  Module::Load::Conditional: 0.0
  Params::Check: 0.0
  Wx: 0.74
  perl: 5.005
version: 0.02
